import { SQUARE_WIDTH } from "features/game/lib/constants";
import type {
  BossTypes,
  DropItemType,
  EnemyConfig,
  MeleeEnemyTypes,
  MiniBossType,
  PhasingEnemyTypes,
} from "../Types";

export const BOSS_DEPTH = 100;
export const ORB_DEPTH = 70;
export const OBSTACLE_SPAWN_BUFFER = SQUARE_WIDTH * 1.5;

// XP values for each drop item type
export const DROP_ITEM_XP_VALUES: Record<DropItemType, number> = {
  blueOrb: 5,
  greenOrb: 12,
  grayOrb: 26,
  yellowOrb: 65,
  purpleOrb: 125,
};

export const ENEMY_BALANCE_STATS = {
  mob1: { HP: 4, SPEED: 20, DAMAGE: 1 },
  mob2: { HP: 8, SPEED: 25, DAMAGE: 3 },
  mob3: { HP: 15, SPEED: 30, DAMAGE: 5 },
  mob4: { HP: 30, SPEED: 20, DAMAGE: 7 },
  mob5: { HP: 50, SPEED: 35, DAMAGE: 10 },

  carnivore_plant: {
    HP: 8,
    SPEED: 15,
    DAMAGE: 2,
  },
  rat: {
    HP: 3,
    SPEED: 35,
    DAMAGE: 1,
  },
  zombie: {
    HP: 10,
    SPEED: 18,
    DAMAGE: 3,
  },
  // Area 2
  imp: {
    HP: 12,
    SPEED: 25,
    DAMAGE: 3,
  },
  slime: {
    HP: 15,
    SPEED: 14,
    DAMAGE: 4,
  },
  // Area 3
  vampire: {
    HP: 18,
    SPEED: 32,
    DAMAGE: 5,
  },
  frankenstein: {
    HP: 35,
    SPEED: 12,
    DAMAGE: 8,
  },
  werewolf: {
    HP: 25,
    SPEED: 38,
    DAMAGE: 6,
  },
  // Area 4
  hellHound: {
    HP: 6,
    SPEED: 15,
    DAMAGE: 8,
  },
  demon: {
    HP: 45,
    SPEED: 25,
    DAMAGE: 10,
  },

  miniBoss1: { HP: 300, SPEED: 20, DAMAGE: 10 },
  miniBoss2: { HP: 300, SPEED: 25, DAMAGE: 10 },
  miniBoss3: { HP: 100, SPEED: 25, DAMAGE: 10 },

  boss1: { HP: 150, SPEED: 25, DAMAGE: 10 },
  boss2: { HP: 350, SPEED: 30, DAMAGE: 12 },
  boss3: { HP: 600, SPEED: 30, DAMAGE: 15 },
} as const;

// Phasing configurations
export const PHASING_CONFIGS: Record<PhasingEnemyTypes, EnemyConfig> = {
  mob1: {
    key: "Mob1",
    scale: 0.8,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.mob1.SPEED,
    hp: ENEMY_BALANCE_STATS.mob1.HP,
    maxHp: ENEMY_BALANCE_STATS.mob1.HP,
    dropItem: "blueOrb",
  },
  mob2: {
    key: "Mob2",
    scale: 0.8,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -12,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 85,
    speed: ENEMY_BALANCE_STATS.mob2.SPEED,
    hp: ENEMY_BALANCE_STATS.mob2.HP,
    maxHp: ENEMY_BALANCE_STATS.mob2.HP,
    dropItem: "blueOrb",
  },
  mob3: {
    key: "Mob3",
    scale: 0.8,
    bodyWidth: 18,
    bodyHeight: 18,
    offsetX: -9,
    offsetY: -9,
    frameStart: 0,
    frameEnd: 12,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.mob3.SPEED,
    hp: ENEMY_BALANCE_STATS.mob3.HP,
    maxHp: ENEMY_BALANCE_STATS.mob3.HP,
    dropItem: "greenOrb",
  },
  mob4: {
    key: "Mob4",
    scale: 0.8,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 11,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.mob4.SPEED,
    hp: ENEMY_BALANCE_STATS.mob4.HP,
    maxHp: ENEMY_BALANCE_STATS.mob4.HP,
    dropItem: "grayOrb",
  },
  mob5: {
    key: "Mob5",
    scale: 0.8,
    bodyWidth: 16,
    bodyHeight: 32,
    offsetX: -8,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 5,
    depth: 90,
    speed: ENEMY_BALANCE_STATS.mob5.SPEED,
    hp: ENEMY_BALANCE_STATS.mob5.HP,
    maxHp: ENEMY_BALANCE_STATS.mob5.HP,
    dropItem: "grayOrb",
  },
};

// Melee configurations
export const MELEE_CONFIGS: Record<MeleeEnemyTypes, EnemyConfig> = {
  carnivore_plant: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  rat: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  zombie: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  imp: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  slime: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  vampire: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  frankenstein: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  werewolf: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  hellHound: {
    key: "hellHound_walk",
    attackKey: "hellHound",
    scale: 0.6,
    bodyWidth: 38,
    bodyHeight: 32,
    offsetX: -19,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 10,
    depth: 70,
    speed: ENEMY_BALANCE_STATS.hellHound.SPEED,
    hp: ENEMY_BALANCE_STATS.hellHound.HP,
    maxHp: ENEMY_BALANCE_STATS.hellHound.HP,
    dropItem: "blueOrb",
  },
  demon: {
    key: "hell_hound",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: 1,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
};

// Boss enemy configurations
export const BOSS_CONFIGS: Record<BossTypes, EnemyConfig> = {
  boss1: {
    key: "Boss1",
    scale: 0.8,
    bodyWidth: 55,
    bodyHeight: 68,
    offsetX: -27.5,
    offsetY: -34,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: 100,
    speed: ENEMY_BALANCE_STATS.boss1.SPEED,
    hp: ENEMY_BALANCE_STATS.boss1.HP,
    maxHp: ENEMY_BALANCE_STATS.boss1.HP,
    dropItem: "yellowOrb",
  },
  boss2: {
    key: "Boss2",
    scale: 0.8,
    bodyWidth: 58,
    bodyHeight: 56,
    offsetX: -28,
    offsetY: -28,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.boss2.SPEED,
    hp: ENEMY_BALANCE_STATS.boss2.HP,
    maxHp: ENEMY_BALANCE_STATS.boss2.HP,
    dropItem: "purpleOrb",
  },
  boss3: {
    key: "Boss3",
    scale: 0.8,
    bodyWidth: 50,
    bodyHeight: 55,
    offsetX: -25,
    offsetY: -27.5,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.boss3.SPEED,
    hp: ENEMY_BALANCE_STATS.boss3.HP,
    maxHp: ENEMY_BALANCE_STATS.boss3.HP,
    dropItem: "purpleOrb",
  },
};

export const MINIBOSS_CONFIGS: Record<MiniBossType, EnemyConfig> = {
  miniBoss1: {
    key: "MiniBoss1",
    attackKey: "MiniBoss1_Attack",
    scale: 0.5,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 80,
    speed: ENEMY_BALANCE_STATS.miniBoss1.SPEED,
    hp: ENEMY_BALANCE_STATS.miniBoss1.HP,
    maxHp: ENEMY_BALANCE_STATS.miniBoss1.HP,
    dropItem: "blueOrb",
  },
  miniBoss2: {
    key: "MiniBoss2",
    attackKey: "MiniBoss2_Attack",
    scale: 0.5,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 85,
    speed: ENEMY_BALANCE_STATS.miniBoss2.SPEED,
    hp: ENEMY_BALANCE_STATS.miniBoss2.HP,
    maxHp: ENEMY_BALANCE_STATS.miniBoss2.HP,
    dropItem: "blueOrb",
  },
  miniBoss3: {
    key: "MiniBoss2",
    attackKey: "MiniBoss1_Attack",
    scale: 0.5,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: 85,
    speed: ENEMY_BALANCE_STATS.miniBoss2.SPEED,
    hp: ENEMY_BALANCE_STATS.miniBoss2.HP,
    maxHp: ENEMY_BALANCE_STATS.miniBoss2.HP,
    dropItem: "blueOrb",
  },
};
