import { SQUARE_WIDTH } from "features/game/lib/constants";
import type {
  BossTypes,
  DropItemType,
  EnemyConfig,
  MeleeEnemyTypes,
  MiniBossType,
  PhasingEnemyTypes,
  StaticRangeEnemyTypes,
} from "../Types";

export const BOSS_DEPTH = 100;
export const ORB_DEPTH = 70;
export const OBSTACLE_SPAWN_BUFFER = SQUARE_WIDTH * 1.5;

// XP values for each drop item type
export const DROP_ITEM_XP_VALUES: Record<DropItemType, number> = {
  blueOrb: 5,
  greenOrb: 12,
  grayOrb: 26,
  yellowOrb: 65,
  purpleOrb: 125,
};

export const ENEMY_BALANCE_STATS = {
  // Area 1
  bat: { HP: 4, SPEED: 20, DAMAGE: 1 }, // phasing
  scarecrow: { HP: 8, SPEED: 20, DAMAGE: 1 }, // static
  carnivore_plant: { HP: 8, SPEED: 15, DAMAGE: 2 }, // melee
  rat: { HP: 4, SPEED: 30, DAMAGE: 3 },
  zombie: { HP: 10, SPEED: 10, DAMAGE: 3 },
  golem: { HP: 100, SPEED: 15, DAMAGE: 10 }, // mini boss
  ent: { HP: 100, SPEED: 25, DAMAGE: 10 },
  minotaur: { HP: 200, SPEED: 25, DAMAGE: 10 }, // boss

  // Area 2
  crow: { HP: 8, SPEED: 25, DAMAGE: 3 }, // phasing
  ghost: { HP: 8, SPEED: 15, DAMAGE: 7 },
  imp: { HP: 100, SPEED: 25, DAMAGE: 5 }, // static
  skeleton: { HP: 3, SPEED: 20, DAMAGE: 3 }, // melee
  slime_red: { HP: 3, SPEED: 15, DAMAGE: 4 },
  slime_green: { HP: 3, SPEED: 15, DAMAGE: 4 },
  slime_blue: { HP: 3, SPEED: 15, DAMAGE: 4 },
  mummy: { HP: 100, SPEED: 15, DAMAGE: 15 }, // mini boss
  living_armor: { HP: 100, SPEED: 20, DAMAGE: 10 },
  witch: { HP: 200, SPEED: 25, DAMAGE: 12 }, // boss

  // Area 3
  gargoyle: { HP: 2, SPEED: 35, DAMAGE: 10 }, // phasing
  cultist: { HP: 100, SPEED: 30, DAMAGE: 5 }, // static
  vampire: { HP: 18, SPEED: 32, DAMAGE: 5 }, // melee
  frankenstein: { HP: 100, SPEED: 15, DAMAGE: 8 },
  werewolf: { HP: 50, SPEED: 38, DAMAGE: 6 },
  headless_horseman: { HP: 300, SPEED: 25, DAMAGE: 10 }, //. mini boss
  medusa: { HP: 100, SPEED: 25, DAMAGE: 10 },
  cerberus: { HP: 600, SPEED: 30, DAMAGE: 15 }, // boss

  // Area 4
  shade: { HP: 15, SPEED: 30, DAMAGE: 5 }, // phasing
  red_stone: { HP: 100, SPEED: 30, DAMAGE: 5 }, // static
  hellHound: { HP: 4, SPEED: 25, DAMAGE: 2 }, // melee
  demon1: { HP: 6, SPEED: 20, DAMAGE: 5 },
  demon2: { HP: 6, SPEED: 15, DAMAGE: 5 },
  sorcerer: { HP: 350, SPEED: 30, DAMAGE: 12 }, // boss
} as const;

const STATIC_RANGE_DEPTH = 1000;
const STATIC_RANGE_SCALE = 0.8;
export const STATIC_RANGE_CONFIG: Record<StaticRangeEnemyTypes, EnemyConfig> = {
  scarecrow: {
    key: "scarecrow",
    attackKey: "scarecrow_attack",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.scarecrow.SPEED,
    hp: ENEMY_BALANCE_STATS.scarecrow.HP,
    maxHp: ENEMY_BALANCE_STATS.scarecrow.HP,
    dropItem: "blueOrb",
  },
  imp: {
    key: "imp",
    attackKey: "imp_attack",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.imp.SPEED,
    hp: ENEMY_BALANCE_STATS.imp.HP,
    maxHp: ENEMY_BALANCE_STATS.imp.HP,
    dropItem: "blueOrb",
  },
  cultist: {
    key: "cultist",
    attackKey: "cultist_attack",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.cultist.SPEED,
    hp: ENEMY_BALANCE_STATS.cultist.HP,
    maxHp: ENEMY_BALANCE_STATS.cultist.HP,
    dropItem: "greenOrb",
  },
  red_stone: {
    key: "red_stone",
    attackKey: "red_stone_attack",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.red_stone.SPEED,
    hp: ENEMY_BALANCE_STATS.red_stone.HP,
    maxHp: ENEMY_BALANCE_STATS.red_stone.HP,
    dropItem: "greenOrb",
  },
};

// Phasing configurations
const PHASING_DEPTH = 120;
const PHASING_SCALE = 0.8;
export const PHASING_CONFIGS: Record<PhasingEnemyTypes, EnemyConfig> = {
  bat: {
    key: "bat1",
    scale: PHASING_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.bat.SPEED,
    hp: ENEMY_BALANCE_STATS.bat.HP,
    maxHp: ENEMY_BALANCE_STATS.bat.HP,
    dropItem: "blueOrb",
  },
  crow: {
    key: "crow",
    scale: PHASING_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.crow.SPEED,
    hp: ENEMY_BALANCE_STATS.crow.HP,
    maxHp: ENEMY_BALANCE_STATS.crow.HP,
    dropItem: "blueOrb",
  },
  ghost: {
    key: "ghost",
    scale: PHASING_SCALE,
    bodyWidth: 18,
    bodyHeight: 18,
    offsetX: -9,
    offsetY: -9,
    frameStart: 0,
    frameEnd: 12,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.ghost.SPEED,
    hp: ENEMY_BALANCE_STATS.ghost.HP,
    maxHp: ENEMY_BALANCE_STATS.ghost.HP,
    dropItem: "greenOrb",
  },
  gargoyle: {
    key: "gargoyle",
    scale: PHASING_SCALE,
    bodyWidth: 48,
    bodyHeight: 48,
    offsetX: -24,
    offsetY: -24,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.gargoyle.SPEED,
    hp: ENEMY_BALANCE_STATS.gargoyle.HP,
    maxHp: ENEMY_BALANCE_STATS.gargoyle.HP,
    dropItem: "grayOrb",
  },
  shade: {
    key: "shade",
    scale: PHASING_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 6,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.shade.SPEED,
    hp: ENEMY_BALANCE_STATS.shade.HP,
    maxHp: ENEMY_BALANCE_STATS.shade.HP,
    dropItem: "grayOrb",
  },
};

// Melee configurations
const MELEE_DEPTH = 110;
const MELEE_SCALE = 0.8;
export const MELEE_CONFIGS: Record<MeleeEnemyTypes, EnemyConfig> = {
  carnivore_plant: {
    key: "carnivore_plant",
    scale: MELEE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.carnivore_plant.SPEED,
    hp: ENEMY_BALANCE_STATS.carnivore_plant.HP,
    maxHp: ENEMY_BALANCE_STATS.carnivore_plant.HP,
    dropItem: "blueOrb",
  },
  rat: {
    key: "rat",
    scale: 1,
    bodyWidth: 22,
    bodyHeight: 16,
    offsetX: -11,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 3,
    frameRate: 12,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.rat.SPEED,
    hp: ENEMY_BALANCE_STATS.rat.HP,
    maxHp: ENEMY_BALANCE_STATS.rat.HP,
    dropItem: "blueOrb",
  },
  zombie: {
    key: "zombie",
    scale: 1,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.zombie.SPEED,
    hp: ENEMY_BALANCE_STATS.zombie.HP,
    maxHp: ENEMY_BALANCE_STATS.zombie.HP,
    dropItem: "blueOrb",
  },
  skeleton: {
    key: "skeleton",
    scale: 1,
    bodyWidth: 14,
    bodyHeight: 17,
    offsetX: -7,
    offsetY: -8.5,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.skeleton.SPEED,
    hp: ENEMY_BALANCE_STATS.skeleton.HP,
    maxHp: ENEMY_BALANCE_STATS.skeleton.HP,
    dropItem: "blueOrb",
  },
  slime_red: {
    key: "slime_red",
    scale: 1,
    bodyWidth: 18,
    bodyHeight: 16,
    offsetX: -9,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 3,
    frameRate: 17,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.slime_red.SPEED,
    hp: ENEMY_BALANCE_STATS.slime_red.HP,
    maxHp: ENEMY_BALANCE_STATS.slime_red.SPEED,
    dropItem: "blueOrb",
  },
  slime_green: {
    key: "slime_green",
    scale: 1,
    bodyWidth: 18,
    bodyHeight: 16,
    offsetX: -9,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 3,
    frameRate: 17,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.slime_green.SPEED,
    hp: ENEMY_BALANCE_STATS.slime_green.HP,
    maxHp: ENEMY_BALANCE_STATS.slime_green.SPEED,
    dropItem: "blueOrb",
  },
  slime_blue: {
    key: "slime_blue",
    scale: 1,
    bodyWidth: 18,
    bodyHeight: 16,
    offsetX: -9,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 3,
    frameRate: 17,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.slime_blue.SPEED,
    hp: ENEMY_BALANCE_STATS.slime_blue.HP,
    maxHp: ENEMY_BALANCE_STATS.slime_blue.SPEED,
    dropItem: "blueOrb",
  },
  vampire: {
    key: "vampire",
    scale: 1,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 15,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.vampire.SPEED,
    hp: ENEMY_BALANCE_STATS.vampire.HP,
    maxHp: ENEMY_BALANCE_STATS.vampire.SPEED,
    dropItem: "blueOrb",
  },
  frankenstein: {
    key: "frankenstein",
    scale: MELEE_SCALE,
    bodyWidth: 39,
    bodyHeight: 50,
    offsetX: -18.5,
    offsetY: -25,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.frankenstein.SPEED,
    hp: ENEMY_BALANCE_STATS.frankenstein.HP,
    maxHp: ENEMY_BALANCE_STATS.frankenstein.SPEED,
    dropItem: "blueOrb",
  },
  werewolf: {
    key: "werewolf",
    scale: MELEE_SCALE,
    bodyWidth: 48,
    bodyHeight: 48,
    offsetX: -24,
    offsetY: -24,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.werewolf.SPEED,
    hp: ENEMY_BALANCE_STATS.werewolf.HP,
    maxHp: ENEMY_BALANCE_STATS.werewolf.SPEED,
    dropItem: "blueOrb",
  },
  hellHound: {
    key: "hellHound",
    scale: MELEE_SCALE,
    bodyWidth: 38,
    bodyHeight: 32,
    offsetX: -19,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.hellHound.SPEED,
    hp: ENEMY_BALANCE_STATS.hellHound.HP,
    maxHp: ENEMY_BALANCE_STATS.hellHound.HP,
    dropItem: "blueOrb",
  },
  demon1: {
    key: "demon1",
    scale: MELEE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.demon1.SPEED,
    hp: ENEMY_BALANCE_STATS.demon1.HP,
    maxHp: ENEMY_BALANCE_STATS.demon1.HP,
    dropItem: "blueOrb",
  },
  demon2: {
    key: "demon2",
    scale: MELEE_SCALE,
    bodyWidth: 40,
    bodyHeight: 40,
    offsetX: -20,
    offsetY: -20,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.demon2.SPEED,
    hp: ENEMY_BALANCE_STATS.demon2.HP,
    maxHp: ENEMY_BALANCE_STATS.demon2.HP,
    dropItem: "blueOrb",
  },
};

const MINI_BOSS_DEPTH = 110;
const MINI_BOSS_SCALE = 0.7;
export const MINIBOSS_CONFIGS: Record<MiniBossType, EnemyConfig> = {
  golem: {
    key: "golem_walk",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 50,
    bodyHeight: 50,
    offsetX: -25,
    offsetY: -25,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.golem.SPEED,
    hp: ENEMY_BALANCE_STATS.golem.HP,
    maxHp: ENEMY_BALANCE_STATS.golem.HP,
    dropItem: "blueOrb",
  },
  ent: {
    key: "ent",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 48,
    bodyHeight: 49,
    offsetX: -24,
    offsetY: -24.5,
    frameStart: 0,
    frameEnd: 9,
    frameRate: 12,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.ent.SPEED,
    hp: ENEMY_BALANCE_STATS.ent.HP,
    maxHp: ENEMY_BALANCE_STATS.ent.HP,
    dropItem: "blueOrb",
  },
  mummy: {
    key: "mummy_walk",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 50,
    bodyHeight: 50,
    offsetX: -25,
    offsetY: -25,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.mummy.SPEED,
    hp: ENEMY_BALANCE_STATS.mummy.HP,
    maxHp: ENEMY_BALANCE_STATS.mummy.HP,
    dropItem: "blueOrb",
  },
  living_armor: {
    key: "living_armor",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 48,
    bodyHeight: 48,
    offsetX: -24,
    offsetY: -24,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.living_armor.SPEED,
    hp: ENEMY_BALANCE_STATS.living_armor.HP,
    maxHp: ENEMY_BALANCE_STATS.living_armor.HP,
    dropItem: "blueOrb",
  },
  headless_horseman: {
    key: "headless_horseman",
    scale: 1,
    bodyWidth: 48,
    bodyHeight: 48,
    offsetX: -24,
    offsetY: -24,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.headless_horseman.SPEED,
    hp: ENEMY_BALANCE_STATS.headless_horseman.HP,
    maxHp: ENEMY_BALANCE_STATS.headless_horseman.HP,
    dropItem: "blueOrb",
  },
  medusa: {
    key: "MiniBoss2",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.medusa.SPEED,
    hp: ENEMY_BALANCE_STATS.medusa.HP,
    maxHp: ENEMY_BALANCE_STATS.medusa.HP,
    dropItem: "blueOrb",
  },
};

// Boss enemy configurations
export const BOSS_CONFIGS: Record<BossTypes, EnemyConfig> = {
  minotaur: {
    key: "minotaur",
    scale: 1,
    bodyWidth: 48,
    bodyHeight: 48,
    offsetX: -24,
    offsetY: -24,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: 100,
    speed: ENEMY_BALANCE_STATS.minotaur.SPEED,
    hp: ENEMY_BALANCE_STATS.minotaur.HP,
    maxHp: ENEMY_BALANCE_STATS.minotaur.HP,
    dropItem: "yellowOrb",
  },
  witch: {
    key: "witch",
    scale: 1,
    bodyWidth: 32,
    bodyHeight: 36,
    offsetX: -16,
    offsetY: -18,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 12,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.witch.SPEED,
    hp: ENEMY_BALANCE_STATS.witch.HP,
    maxHp: ENEMY_BALANCE_STATS.witch.HP,
    dropItem: "purpleOrb",
  },
  cerberus: {
    key: "Boss3",
    scale: 1,
    bodyWidth: 50,
    bodyHeight: 55,
    offsetX: -25,
    offsetY: -27.5,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.cerberus.SPEED,
    hp: ENEMY_BALANCE_STATS.cerberus.HP,
    maxHp: ENEMY_BALANCE_STATS.cerberus.HP,
    dropItem: "purpleOrb",
  },
  sorcerer: {
    key: "sorcerer",
    scale: 1,
    bodyWidth: 48,
    bodyHeight: 48,
    offsetX: -24,
    offsetY: -24,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.sorcerer.SPEED,
    hp: ENEMY_BALANCE_STATS.sorcerer.HP,
    maxHp: ENEMY_BALANCE_STATS.sorcerer.HP,
    dropItem: "purpleOrb",
  },
};
