import { SQUARE_WIDTH } from "features/game/lib/constants";
import type {
  BossTypes,
  DropItemType,
  EnemyConfig,
  MeleeEnemyTypes,
  MiniBossType,
  PhasingEnemyTypes,
  StaticRangeEnemyTypes,
} from "../Types";

export const BOSS_DEPTH = 100;
export const ORB_DEPTH = 70;
export const OBSTACLE_SPAWN_BUFFER = SQUARE_WIDTH * 1.5;

// XP values for each drop item type
export const DROP_ITEM_XP_VALUES: Record<DropItemType, number> = {
  blueOrb: 5,
  greenOrb: 12,
  grayOrb: 26,
  yellowOrb: 65,
  purpleOrb: 125,
};

export const ENEMY_BALANCE_STATS = {
  // Phasing
  mob1: { HP: 4, SPEED: 20, DAMAGE: 1 },
  mob2: { HP: 8, SPEED: 25, DAMAGE: 3 },
  mob3: { HP: 15, SPEED: 30, DAMAGE: 5 },
  mob4: { HP: 30, SPEED: 20, DAMAGE: 7 },
  mob5: { HP: 50, SPEED: 35, DAMAGE: 10 },

  // Static Range
  scarecrow: { HP: 8, SPEED: 20, DAMAGE: 1 },
  skeleton: { HP: 8, SPEED: 25, DAMAGE: 3 },
  cultist: { HP: 100, SPEED: 30, DAMAGE: 5 },

  // Melee
  carnivore_plant: { HP: 8, SPEED: 15, DAMAGE: 2 },
  rat: { HP: 3, SPEED: 35, DAMAGE: 1 },
  zombie: { HP: 10, SPEED: 18, DAMAGE: 3 },
  imp: { HP: 12, SPEED: 25, DAMAGE: 3 },
  slime: { HP: 15, SPEED: 14, DAMAGE: 4 },
  vampire: { HP: 18, SPEED: 32, DAMAGE: 5 },
  frankenstein: { HP: 35, SPEED: 12, DAMAGE: 8 },
  werewolf: { HP: 25, SPEED: 38, DAMAGE: 6 },
  hellHound: { HP: 4, SPEED: 15, DAMAGE: 2 },
  demon1: { HP: 6, SPEED: 15, DAMAGE: 5 },
  demon2: { HP: 6, SPEED: 15, DAMAGE: 5 },

  // MiniBoss
  golem: { HP: 500, SPEED: 20, DAMAGE: 10 },
  ent: { HP: 100, SPEED: 25, DAMAGE: 10 },
  mummy: { HP: 500, SPEED: 30, DAMAGE: 15 },
  living_armor: { HP: 100, SPEED: 25, DAMAGE: 10 },
  headless_horseman: { HP: 100, SPEED: 25, DAMAGE: 10 },
  medusa: { HP: 100, SPEED: 25, DAMAGE: 10 },

  // Boss
  boss1: { HP: 150, SPEED: 25, DAMAGE: 10 },
  boss2: { HP: 350, SPEED: 30, DAMAGE: 12 },
  boss3: { HP: 600, SPEED: 30, DAMAGE: 15 },
} as const;

const STATIC_RANGE_DEPTH = 1000;
const STATIC_RANGE_SCALE = 0.8;
export const STATIC_RANGE_CONFIG: Record<StaticRangeEnemyTypes, EnemyConfig> = {
  scarecrow: {
    key: "Mob1",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.scarecrow.SPEED,
    hp: ENEMY_BALANCE_STATS.scarecrow.HP,
    maxHp: ENEMY_BALANCE_STATS.scarecrow.HP,
    dropItem: "blueOrb",
  },
  skeleton: {
    key: "Mob2",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -12,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.mob2.SPEED,
    hp: ENEMY_BALANCE_STATS.mob2.HP,
    maxHp: ENEMY_BALANCE_STATS.mob2.HP,
    dropItem: "blueOrb",
  },
  cultist: {
    key: "cultist",
    attackKey: "cultist_attack",
    scale: STATIC_RANGE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -8,
    frameStart: 0,
    frameEnd: 10,
    frameRate: 10,
    depth: STATIC_RANGE_DEPTH,
    speed: ENEMY_BALANCE_STATS.cultist.SPEED,
    hp: ENEMY_BALANCE_STATS.cultist.HP,
    maxHp: ENEMY_BALANCE_STATS.cultist.HP,
    dropItem: "greenOrb",
  },
};

// Phasing configurations
const PHASING_DEPTH = 120;
const PHASING_SCALE = 0.8;
export const PHASING_CONFIGS: Record<PhasingEnemyTypes, EnemyConfig> = {
  mob1: {
    key: "Mob1",
    scale: PHASING_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.mob1.SPEED,
    hp: ENEMY_BALANCE_STATS.mob1.HP,
    maxHp: ENEMY_BALANCE_STATS.mob1.HP,
    dropItem: "blueOrb",
  },
  mob2: {
    key: "Mob2",
    scale: PHASING_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: -8,
    offsetY: -12,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.mob2.SPEED,
    hp: ENEMY_BALANCE_STATS.mob2.HP,
    maxHp: ENEMY_BALANCE_STATS.mob2.HP,
    dropItem: "blueOrb",
  },
  mob3: {
    key: "Mob3",
    scale: PHASING_SCALE,
    bodyWidth: 18,
    bodyHeight: 18,
    offsetX: -9,
    offsetY: -9,
    frameStart: 0,
    frameEnd: 12,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.mob3.SPEED,
    hp: ENEMY_BALANCE_STATS.mob3.HP,
    maxHp: ENEMY_BALANCE_STATS.mob3.HP,
    dropItem: "greenOrb",
  },
  mob4: {
    key: "Mob4",
    scale: PHASING_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 11,
    frameRate: 10,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.mob4.SPEED,
    hp: ENEMY_BALANCE_STATS.mob4.HP,
    maxHp: ENEMY_BALANCE_STATS.mob4.HP,
    dropItem: "grayOrb",
  },
  mob5: {
    key: "Mob5",
    scale: PHASING_SCALE,
    bodyWidth: 16,
    bodyHeight: 32,
    offsetX: -8,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 5,
    depth: PHASING_DEPTH,
    speed: ENEMY_BALANCE_STATS.mob5.SPEED,
    hp: ENEMY_BALANCE_STATS.mob5.HP,
    maxHp: ENEMY_BALANCE_STATS.mob5.HP,
    dropItem: "grayOrb",
  },
};

// Melee configurations
const MELEE_DEPTH = 110;
const MELEE_SCALE = 0.6;
export const MELEE_CONFIGS: Record<MeleeEnemyTypes, EnemyConfig> = {
  carnivore_plant: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  rat: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  zombie: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  imp: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  slime: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  vampire: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  frankenstein: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  werewolf: {
    key: "hell_hound",
    scale: MELEE_SCALE,
    bodyWidth: 16,
    bodyHeight: 16,
    offsetX: 0,
    offsetY: 0,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: 20,
    hp: 4,
    maxHp: 4,
    dropItem: "blueOrb",
  },
  hellHound: {
    key: "hellHound_walk",
    attackKey: "hellHound",
    scale: MELEE_SCALE,
    bodyWidth: 38,
    bodyHeight: 32,
    offsetX: -19,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 4,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.hellHound.SPEED,
    hp: ENEMY_BALANCE_STATS.hellHound.HP,
    maxHp: ENEMY_BALANCE_STATS.hellHound.HP,
    dropItem: "blueOrb",
  },
  demon1: {
    key: "demon1",
    scale: MELEE_SCALE,
    bodyWidth: 32,
    bodyHeight: 32,
    offsetX: -16,
    offsetY: -16,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.demon1.SPEED,
    hp: ENEMY_BALANCE_STATS.demon1.HP,
    maxHp: ENEMY_BALANCE_STATS.demon1.HP,
    dropItem: "blueOrb",
  },
  demon2: {
    key: "demon2",
    scale: MELEE_SCALE,
    bodyWidth: 40,
    bodyHeight: 40,
    offsetX: -20,
    offsetY: -20,
    frameStart: 0,
    frameEnd: 5,
    frameRate: 10,
    depth: MELEE_DEPTH,
    speed: ENEMY_BALANCE_STATS.demon2.SPEED,
    hp: ENEMY_BALANCE_STATS.demon2.HP,
    maxHp: ENEMY_BALANCE_STATS.demon2.HP,
    dropItem: "blueOrb",
  },
};

// Boss enemy configurations
export const BOSS_CONFIGS: Record<BossTypes, EnemyConfig> = {
  boss1: {
    key: "Boss1",
    scale: 0.8,
    bodyWidth: 55,
    bodyHeight: 68,
    offsetX: -27.5,
    offsetY: -34,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: 100,
    speed: ENEMY_BALANCE_STATS.boss1.SPEED,
    hp: ENEMY_BALANCE_STATS.boss1.HP,
    maxHp: ENEMY_BALANCE_STATS.boss1.HP,
    dropItem: "yellowOrb",
  },
  boss2: {
    key: "Boss2",
    scale: 0.8,
    bodyWidth: 58,
    bodyHeight: 56,
    offsetX: -28,
    offsetY: -28,
    frameStart: 0,
    frameEnd: 7,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.boss2.SPEED,
    hp: ENEMY_BALANCE_STATS.boss2.HP,
    maxHp: ENEMY_BALANCE_STATS.boss2.HP,
    dropItem: "purpleOrb",
  },
  boss3: {
    key: "Boss3",
    scale: 0.8,
    bodyWidth: 50,
    bodyHeight: 55,
    offsetX: -25,
    offsetY: -27.5,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.boss3.SPEED,
    hp: ENEMY_BALANCE_STATS.boss3.HP,
    maxHp: ENEMY_BALANCE_STATS.boss3.HP,
    dropItem: "purpleOrb",
  },
};

const MINI_BOSS_DEPTH = 110;
const MINI_BOSS_SCALE = 0.7;
export const MINIBOSS_CONFIGS: Record<MiniBossType, EnemyConfig> = {
  golem: {
    key: "golem_walk",
    attackKey: "golem_attack",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 50,
    bodyHeight: 50,
    offsetX: -25,
    offsetY: -25,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.golem.SPEED,
    hp: ENEMY_BALANCE_STATS.golem.HP,
    maxHp: ENEMY_BALANCE_STATS.golem.HP,
    dropItem: "blueOrb",
  },
  ent: {
    key: "MiniBoss2",
    attackKey: "MiniBoss2_Attack",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.ent.SPEED,
    hp: ENEMY_BALANCE_STATS.ent.HP,
    maxHp: ENEMY_BALANCE_STATS.ent.HP,
    dropItem: "blueOrb",
  },
  mummy: {
    key: "mummy_walk",
    attackKey: "mummy_attack",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 50,
    bodyHeight: 50,
    offsetX: -25,
    offsetY: -25,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.mummy.SPEED,
    hp: ENEMY_BALANCE_STATS.mummy.HP,
    maxHp: ENEMY_BALANCE_STATS.mummy.HP,
    dropItem: "blueOrb",
  },
  living_armor: {
    key: "MiniBoss2",
    attackKey: "MiniBoss1_Attack",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.living_armor.SPEED,
    hp: ENEMY_BALANCE_STATS.living_armor.HP,
    maxHp: ENEMY_BALANCE_STATS.living_armor.HP,
    dropItem: "blueOrb",
  },
  headless_horseman: {
    key: "MiniBoss2",
    attackKey: "MiniBoss1_Attack",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.headless_horseman.SPEED,
    hp: ENEMY_BALANCE_STATS.headless_horseman.HP,
    maxHp: ENEMY_BALANCE_STATS.headless_horseman.HP,
    dropItem: "blueOrb",
  },
  medusa: {
    key: "MiniBoss2",
    attackKey: "MiniBoss1_Attack",
    scale: MINI_BOSS_SCALE,
    bodyWidth: 64,
    bodyHeight: 64,
    offsetX: -32,
    offsetY: -32,
    frameStart: 0,
    frameEnd: 8,
    frameRate: 10,
    depth: MINI_BOSS_DEPTH,
    speed: ENEMY_BALANCE_STATS.medusa.SPEED,
    hp: ENEMY_BALANCE_STATS.medusa.HP,
    maxHp: ENEMY_BALANCE_STATS.medusa.HP,
    dropItem: "blueOrb",
  },
};
